"""
Constants and configuration values for the circuit designer application.
"""

# Grid settings
GRID_SPACING_DEFAULT = 40
GRID_PLACEMENT_CELLS = 15
GRID_BORDER_THICKNESS_CELLS = 1
TARGET_HEIGHT_BASELINE = 600

# Visual appearance
GRID_LINE_COLOR = (220, 220, 220)
GRID_INNER_BORDER_COLOR = (180, 180, 180)
GRID_OUTER_BORDER_COLOR = (80, 80, 80)
GRID_SHADED_BORDER_COLOR = (50, 50, 50, 40)

WIRE_COLOR = (0, 0, 255)
WIRE_WIDTH = 3
WIRE_HOVER_COLOR = (100, 100, 255)
WIRE_HOVER_WIDTH = 4
WIRE_SELECTED_COLOR = (255, 0, 0)
WIRE_SELECTED_WIDTH = 4

COMPONENT_BG_COLOR = (240, 240, 255)
COMPONENT_BORDER_COLOR = (0, 0, 0)
COMPONENT_BORDER_WIDTH = 2
COMPONENT_SELECTED_COLOR = (255, 0, 0)
COMPONENT_SELECTED_WIDTH = 3

# Connection points
CONNECTION_POINT_RADIUS = 5
CONNECTION_POINT_IN_COLOR = (0, 150, 0)  # Green for input
CONNECTION_POINT_OUT_COLOR = (220, 140, 0)  # Orange for output
CONNECTION_POINT_TERMINAL_COLOR = (255, 0, 0)  # Red for terminal

# Bend points
BEND_POINT_RADIUS = 4
BEND_POINT_COLOR = (0, 200, 0)
BEND_POINT_HOVER_COLOR = (100, 255, 100)

# Z-values for layering
Z_VALUE_GRID = 0
Z_VALUE_WIRE = 10
Z_VALUE_COMPONENT = 50
Z_VALUE_BEND_POINT = 100
Z_VALUE_CONNECTION_POINT = 110
Z_VALUE_SELECTED = 500

# Zoom settings
ZOOM_FACTOR = 1.15
ZOOM_MIN = 0.1
ZOOM_MAX = 5.0

# Undo/Redo
UNDO_STACK_LIMIT = 50

# Clipboard
CLIPBOARD_MAX_ITEMS = 100

# Project settings
PROJECT_THUMBNAIL_SIZE = 200

# Simulation
DEFAULT_TEMPERATURE = 25
DEFAULT_LED_THRESHOLD = 1.5  # Volts
DEFAULT_LED_RESISTANCE = 100  # Ohms
SWITCH_OPEN_RESISTANCE = 1e9  # Very high
SWITCH_CLOSED_RESISTANCE = 0.001  # Very low

# File settings
PROJECT_FILE_EXTENSION = '.ecis'
PROJECT_VERSION = '1.0'

# Tolerances
POSITION_TOLERANCE = 0.1  # pixels
GRID_SNAP_TOLERANCE = 0.01  # pixels
